### ISSUE TITLE
BitBucket REST API causes generator explosion

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jskov/openapi-jaxrs-client#489]
On REST API https://dac-static.atlassian.com/server/bitbucket/8.15.swagger.v3.json?_v=1.466.0

Unclear as yet which part of the API triggers the explosion.

```
2023-12-05T13:15:59.961+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getType()" because "schema" is null       
2023-12-05T13:15:59.961+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.openapi.TypeConverter.reference(TypeConverter.java:171)                                                       
2023-12-05T13:15:59.961+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.openapi.TypeConverter.toReference(TypeConverter.java:124)                                                     
2023-12-05T13:15:59.961+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.openapi.ApiTransformer.toParam(ApiTransformer.java:281)                                
2023-12-05T13:15:59.961+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.openapi.ApiTransformer.getParameters(ApiTransformer.java:269)                  
2023-12-05T13:15:59.961+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.openapi.ApiTransformer.processOp(ApiTransformer.java:117)                     
2023-12-05T13:15:59.961+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.openapi.ApiTransformer.lambda$processPath$0(ApiTransformer.java:107)          
2023-12-05T13:15:59.962+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.openapi.ApiTransformer.processPath(ApiTransformer.java:107)               
2023-12-05T13:15:59.962+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.openapi.ApiTransformer.transform(ApiTransformer.java:97)                  
2023-12-05T13:15:59.962+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.openapi.Parser.parse(Parser.java:114)                           
2023-12-05T13:15:59.962+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at dk.mada.jaxrs.generator.mpclient.Generator.generateClient(Generator.java:51)  
2023-12-05T13:15:59.962+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 33 more                                                                                                                                                                               

```

**Comment by jskov** [comment]
Fixed by #635 and #636
